databases:
  - name: antic-database
    plan: free

services:
  - type: web
    name: ac3-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ac3_backend.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: antic-database
          property: connectionString