# Generated by Django 5.2.5 on 2025-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
