# Generated by Django 5.2.5 on 2025-08-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_checklistcategory_checklistitem_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
